### ISSUE TITLE
Automatically Generating Custom User Pages for a Client Portal

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#109]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Automatically Generating Custom User Pages for a Client Portal
categories: tutorials
tags: 
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/109
```
---
This tutorial would explain how to programmatically generate a custom user page for Client Portals (see this video: https://www.youtube.com/watch?v=BBltDUopo1U) so that when a user signs up, a new WordPress page, specifically for them, is automatically created.
