### ISSUE TITLE
What are PayPal Error and Warning Codes?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#190]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: What are PayPal Error and Warning Codes?
categories: questions
tags: 
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/190
```
---

https://developer.paypal.com/docs/classic/api/errorcodes/

[an s2Member KB article dedicated to referencing that article, and perhaps explaining an little how many error and warning codes that a site owner may see being thrown by s2Member are actually coming from PayPal and being displayed by s2Member]
