### ISSUE TITLE
How can I differentiate between monthly and yearly subscribers?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#202]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: How can I differentiate between monthly and yearly subscribers?
categories: questions
tags: 
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/202
```
---
The easiest way to differentiate these would be to utilize the Custom Capabilities attribute (`ccaps=""`) in your Pro-Form shortcode. 

For example, on your Monthly Pro-Form, you could put `ccaps="monthly"` and on your Yearly Pro-Form you could put `ccaps="yearly"`. Then whenever someone signs up with one of those Pro-Forms, their account will contain either the `monthly` or the `yearly` Custom Capability. The Custom Capability column will also be visible from the User List, making it easy to identify who is a yearly subscriber and who is a monthly subscriber.
