### ISSUE TITLE
Is s2Member compatible with multilingual plugins used for translation?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#210]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Is s2Member compatible with multilingual plugins used for translation?
categories: questions
tags: 
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/210
```
---
s2Member is a WordPress plugin that is compatible with [WordPress I18n](http://codex.wordpress.org/I18n_for_WordPress_Developers), which makes translation possible through popular multilingual plugins such as [WPML](http://wpml.org/). You shouldn't have any issues creating a multilingual s2Member site.
