### ISSUE TITLE
How do members renew or extend their membership?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#216]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: How do members renew or extend their membership?
categories: questions
tags: eot-time, pro-forms, billing-modification
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/216
```
---
> Question - is there a work flow for users to extend their EOT or renew their membership before expiration? I cannot find any info on renewal in the knowledge base (I found upgrade/downgrade stuff!)

[needs to be drafted]

Related: [How do I display the EOT Date/Time?](http://s2member.com/kb-article/how-do-i-display-the-eot-on-my-login-welcome-page/)
