### ISSUE TITLE
What are the s2Member directories?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#230]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: What are the s2Member Folders / Directories?
categories: questions
tags: uninstalling,
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/230
```
---

## See [What are the s2Member Folders / Directories?](http://s2member.com/kb-article/how-do-i-uninstall-s2member/#toc-cbe147cc)
