### ISSUE TITLE
How can I use Gravity Forms with s2Member?

### ISSUE THREAD

**Issue by patdumond** [websharks/s2member-kb#272]
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue draft and either questions or tutorials
- [ ] Add required YAML configuration
- [ ] Add Tags for this KB Article to the YAML config (see YAML Keys (Explained))
- [ ] Edit and finalize draft for publishing (remove draft label, add draft-finalized label)
- [ ] Create Markdown file for this Article (remove draft-finalized label, add pending label)
- [ ] Publish KB Article (remove pending label, add published label; leave this step for the Project Lead)

```yaml
title: How can I use Gravity Forms with s2Member?
categories: tutorials
tags: third-party plugins
author: patdumond
github-issue: 
```
