### ISSUE TITLE
Is it possible to bypass the 20% limit on upgrade imposed by papal using s2Member Pro?

### ISSUE THREAD

**Issue by renzms** [websharks/s2member-kb#288]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

```yaml
title: Is it possible to bypass the 20% limit on upgrade imposed by papal using s2Member Pro?categories: question
tags: 
author: renzms
github-issue: https://github.com/websharks/s2member/issues/834
```
---
