### ISSUE TITLE
Bitcoin and Stripe Integration

### ISSUE THREAD

**Issue by renzms** [websharks/s2member-kb#292]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

```yaml
title: Bitcoin and Stripe Integration
categories: tutorials
tags: 
author: renzms
github-issue: https://github.com/websharks/s2member-kb/issues/278
```
---

### Stripe Limitations

Stripe and Bitcoin can only be used for Buy Now buttons, not recurring payments in s2Member.

Bitcoin is only supported by a US Dollar account and Stripe will receive in Bitcoin but convert to USD. There would also be a fee charged by Stripe for every transaction.

____

https://stripe.com/bitcoin
