### ISSUE TITLE
s2Member Shortcode Callback Functions

### ISSUE THREAD

**Issue by renzms** [websharks/s2member-kb#305]
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

```yaml
title: s2Member Shortcode Callback Functions
categories: tutorials
tags: 
author: renzms
github-issue: https://github.com/websharks/s2member-kb/issues/
```
---

https://github.com/websharks/s2member/blob/000000-dev/s2member/includes/codes.inc.php
