### ISSUE TITLE
How can I set a custom redirect after profile updates?

### ISSUE THREAD

**Issue by kristineds** [websharks/s2member-kb#307]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

- [ ] Add introduction

```yaml
title: How can I set a custom redirect after profile updates?
categories: Questions
tags: mu-plugins-hacks, s2member-profile, member-profile-modifications
author: kristineds
github-issue: https://github.com/websharks/s2member-kb/issues/#
```
_This is a work in progress._

---

[intro]

----

> I am using [s2Member-Profile /], is it possible to add a hook to redirect to a specific page on update profile only? Is there anything i can add to the shortcode to specifically say where to redirect to?

For Profile Redirects, you can use an MU-Plugin like this:

```php
<?php
add_action('ws_plugin__s2member_after_handle_profile_modifications', '__s2_redirect_after_profile_save');

function __s2_redirect_after_profile_save() {
    wp_redirect(home_url()); // this could be any URL, e.g., wp_redirect("http://example.com/");
}
```

---

#### See also:

- [Configuring s2Member General Options](http://s2member.com/kb-article/configuring-s2member-general-options)
- [[s2Member-Profile /] Shortcode](https://s2member.com/kb-article/s2member-profile-shortcode/)
