### ISSUE TITLE
How can I embed a login form on my site?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#49]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

```yaml
title: How can I embed a login form on my site?
categories: questions
tags: login-registration, pro-login-widget
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/49
toc-enable: false
```
---
**Question:** How can I embed a login form on my site?

**Answer:** The Login Form itself is part of WordPress, not part of s2Member. However, s2Member Pro does come with the Pro-Login Widget (please see: **Dashboard ⥱ Appearance ⥱ Widgets ⥱ s2Member Pro Login Widget**), which you can add to any Widgetized area of your theme. 

If you require a separate login form that you can embed into a page on your site, I recommend posting a question on the [WordPress Support Forum](http://wordpress.org/support/) or searching the [WordPress Plugins Repository](https://wordpress.org/plugins/) for a free plugin that does what you want. Again, the Login Form is not part of s2Member but part of WordPress itself.
