### ISSUE TITLE
How do I setup dynamic membership pricing?

### ISSUE THREAD

**Issue by raamdev** [websharks/s2member-kb#74]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

```yaml
title: How do I setup dynamic membership pricing?
categories: questions
tags: pro-forms
author: raamdev
github-issue: https://github.com/websharks/s2member-kb/issues/74
```
---

**Question:** How do I setup dynamic membership pricing?

See original question: https://wordpress.org/support/topic/dynamic-membership-pricing-like-dime-sale?replies=1

**Answer:** _[needs to be drafted]_
